In [3]:
import pandas as pd
train = pd.read_csv("train.csv")
breed_labels = pd.read_csv("breed_labels.csv")
color_labels = pd.read_csv("color_labels.csv")
state_labels = pd.read_csv("state_labels.csv")

In [5]:
columns = ["Breed1","Breed2","Color2","Color2","Color3","State"]
train[columns].isnull().sum()

Breed1    0
Breed2    0
Color2    0
Color2    0
Color3    0
State     0
dtype: int64

In [7]:
breed_map = dict(zip(breed_labels.BreedID, breed_labels.BreedName))
color_map = dict(zip(color_labels.ColorID, color_labels.ColorName))
state_map = dict(zip(state_labels.StateID, state_labels.StateName))

In [8]:
train["Breed1"] = train["Breed1"].map(breed_map)
train["Breed2"] = train["Breed2"].map(breed_map)

train["Color1"] = train["Color1"].map(color_map)
train["Color2"] = train["Color2"].map(color_map)
train["Color3"] = train["Color3"].map(color_map)

train["State"] = train["State"].map(state_map)

In [9]:
train.to_csv("pets_clean.csv", index=False)

In [13]:
pets = pd.read_csv("pets_clean.csv")
pets.head()

,Type,Name,Age,Breed1,Breed2,Gender,Color1,Color2,Color3,MaturitySize,...,Health,Quantity,Fee,State,RescuerID,VideoAmt,Description,PetID,PhotoAmt,AdoptionSpeed
0,2,Nibble,3,Tabby,NaN,1,Black,White,NaN,1,...,1,1,100,Maharashtra,8480853f516546f6cf33aa88cd76c379,0,Nibble is a 3+ month old ball of cuteness. He ...,86e1089a3,1.0,2
1,2,No Name Yet,1,Domestic Medium Hair,NaN,1,Black,Brown,NaN,2,...,1,1,0,Uttarakhand,3082c7125d8fb66f7dd4bff4192c8b14,0,I just found it alone yesterday near my apartm...,6296e909a,2.0,0
2,1,Brisco,1,Mixed Breed,NaN,1,Brown,White,NaN,2,...,1,1,0,Maharashtra,fa90fa5b1ee11c86938398b60abc32cb,0,Their pregnant mother was dumped by her irresp...,3422e4906,7.0,3
3,1,Miko,4,Mixed Breed,NaN,2,Black,Brown,NaN,2,...,1,1,150,Uttarakhand,9238e4f44c71a75282e62f7136c6b240,0,"Good guard dog, very alert, active, obedience ...",5842f1ff5,8.0,2
4,1,Hunter,1,Mixed Breed,NaN,1,Black,NaN,NaN,2,...,1,1,0,Maharashtra,95481e953f8aed9ec3d16fc4509537e8,0,This handsome yet cute boy is up for adoption....,850a43f90,3.0,2

In [49]:
columns_to_keep = [
    "PetID",
    "Type",
    "Name",
    "Age",
    "Breed1",
    "Breed2",
    "Gender",
    "Color1",
    "Color2",
    "Color3",
    "MaturitySize",
    "FurLength",
    "Vaccinated",
    "Dewormed",
    "Sterilized",
    "Health",
    "Quantity",
    "Fee",
    "State",
    "Description"
]

pets = pets[columns_to_keep]

In [50]:
new_columns = [
    "energy_level",
    "space_requirement",
    "grooming_level",
    "experience_required",
    "time_requirement",
    "kid_friendly",
    "pet_friendly",
    "special_needs"
]

for col in new_columns:
    pets[col] = None

In [51]:
def get_energy(age):
    if age <= 12:
        return "high"
    elif age <= 60:
        return "medium"
    else:
        return "low"

pets["energy_level"] = pets["Age"].apply(get_energy)

In [52]:
size_map = {
    1: "small",
    2: "medium",
    3: "large",
    4: "extra_large"
}

pets["space_requirement"] = pets["MaturitySize"].map(size_map)

In [53]:
fur_map = {
    1: "low",
    2: "medium",
    3: "high"
}

pets["grooming_level"] = pets["FurLength"].map(fur_map)

In [54]:
def get_experience(row):
    if row["Health"] != 1:
        return "experienced"
    elif row["Age"] < 6:
        return "intermediate"
    else:
        return "beginner"

pets["experience_required"] = pets.apply(get_experience, axis=1)

In [55]:
pets["time_requirement"] = pets["energy_level"] #Pets with high enery need more attention

In [56]:
def kid_friendly(age):
    if age < 3:
        return "maybe"
    else:
        return "yes"

pets["kid_friendly"] = pets["Age"].apply(kid_friendly)

In [59]:
pets["pet_friendly"] = "unknown"

In [58]:
pets["special_needs"] = pets["Health"].apply(lambda x: "yes" if x != 1 else "no")

In [60]:
pets.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14993 entries, 0 to 14992
Data columns (total 28 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   PetID                14993 non-null  object
 1   Type                 14993 non-null  int64
 2   Name                 13728 non-null  object
 3   Age                  14993 non-null  int64
 4   Breed1               14988 non-null  object
 5   Breed2               4231 non-null   object
 6   Gender               14993 non-null  int64
 7   Color1               14993 non-null  object
 8   Color2               10522 non-null  object
 9   Color3               4389 non-null   object
 10  MaturitySize         14993 non-null  int64
 11  FurLength            14993 non-null  int64
 12  Vaccinated           14993 non-null  int64
 13  Dewormed             14993 non-null  int64
 14  Sterilized           14993 non-null  int64
 15  Health               14993 non-null  int64
 16  Quantity             14993 non-null  int64
 17  Fee                  14993 non-null  int64
 18  State                14993 non-null  object
 19  Description          14980 non-null  object
 20  energy_level         14993 non-null  object
 21  space_requirement    14993 non-null  object
 22  grooming_level       14993 non-null  object
 23  experience_required  14993 non-null  object
 24  time_requirement     14993 non-null  object
 25  kid_friendly         14993 non-null  object
 26  pet_friendly         14993 non-null  object
 27  special_needs        14993 non-null  object
dtypes: int64(11), object(17)
memory usage: 3.2+ MB

In [74]:
train = pd.read_csv("train.csv")
pets["Gender"] = train["Gender"]

In [75]:
pets["Gender"].unique()

array([1, 2, 3], dtype=int64)

In [76]:
gender_map = {
    1: "male",
    2: "female",
    3: "mixed"
}
pets["Gender"] = pets["Gender"].map(gender_map)

In [77]:
pets.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14993 entries, 0 to 14992
Data columns (total 28 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   PetID                14993 non-null  object
 1   Type                 0 non-null      object
 2   Name                 13728 non-null  object
 3   Age                  14993 non-null  int64
 4   Breed1               14988 non-null  object
 5   Breed2               4231 non-null   object
 6   Gender               14993 non-null  object
 7   Color1               14993 non-null  object
 8   Color2               10522 non-null  object
 9   Color3               4389 non-null   object
 10  MaturitySize         14993 non-null  int64
 11  FurLength            14993 non-null  int64
 12  Vaccinated           14993 non-null  int64
 13  Dewormed             14993 non-null  int64
 14  Sterilized           14993 non-null  int64
 15  Health               14993 non-null  int64
 16  Quantity             14993 non-null  int64
 17  Fee                  14993 non-null  int64
 18  State                14993 non-null  object
 19  Description          14980 non-null  object
 20  energy_level         14993 non-null  object
 21  space_requirement    14993 non-null  object
 22  grooming_level       14993 non-null  object
 23  experience_required  14993 non-null  object
 24  time_requirement     14993 non-null  object
 25  kid_friendly         14993 non-null  object
 26  pet_friendly         14993 non-null  object
 27  special_needs        14993 non-null  object
dtypes: int64(9), object(19)
memory usage: 3.2+ MB

In [83]:
type_map = {
    1: "dog",
    2: "cat"
}

pets["Type"] = train["Type"].map(type_map)

In [71]:
pets.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14993 entries, 0 to 14992
Data columns (total 28 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   PetID                14993 non-null  object
 1   Type                 0 non-null      object
 2   Name                 13728 non-null  object
 3   Age                  14993 non-null  int64
 4   Breed1               14988 non-null  object
 5   Breed2               4231 non-null   object
 6   Gender               0 non-null      object
 7   Color1               14993 non-null  object
 8   Color2               10522 non-null  object
 9   Color3               4389 non-null   object
 10  MaturitySize         14993 non-null  int64
 11  FurLength            14993 non-null  int64
 12  Vaccinated           14993 non-null  int64
 13  Dewormed             14993 non-null  int64
 14  Sterilized           14993 non-null  int64
 15  Health               14993 non-null  int64
 16  Quantity             14993 non-null  int64
 17  Fee                  14993 non-null  int64
 18  State                14993 non-null  object
 19  Description          14980 non-null  object
 20  energy_level         14993 non-null  object
 21  space_requirement    14993 non-null  object
 22  grooming_level       14993 non-null  object
 23  experience_required  14993 non-null  object
 24  time_requirement     14993 non-null  object
 25  kid_friendly         14993 non-null  object
 26  pet_friendly         14993 non-null  object
 27  special_needs        14993 non-null  object
dtypes: int64(9), object(19)
memory usage: 3.2+ MB

In [84]:
pd.set_option('display.max_columns', None)
pets.head()

,PetID,Type,Name,Age,Breed1,Breed2,Gender,Color1,Color2,Color3,MaturitySize,FurLength,Vaccinated,Dewormed,Sterilized,Health,Quantity,Fee,State,Description,energy_level,space_requirement,grooming_level,experience_required,time_requirement,kid_friendly,pet_friendly,special_needs
0,86e1089a3,cat,Nibble,3,Tabby,NaN,male,Black,White,NaN,1,1,2,2,2,1,1,100,Maharashtra,Nibble is a 3+ month old ball of cuteness. He ...,high,small,low,intermediate,high,yes,unknown,no
1,6296e909a,cat,No Name Yet,1,Domestic Medium Hair,NaN,male,Black,Brown,NaN,2,2,3,3,3,1,1,0,Uttarakhand,I just found it alone yesterday near my apartm...,high,medium,medium,intermediate,high,maybe,unknown,no
2,3422e4906,dog,Brisco,1,Mixed Breed,NaN,male,Brown,White,NaN,2,2,1,1,2,1,1,0,Maharashtra,Their pregnant mother was dumped by her irresp...,high,medium,medium,intermediate,high,maybe,unknown,no
3,5842f1ff5,dog,Miko,4,Mixed Breed,NaN,female,Black,Brown,NaN,2,1,1,1,2,1,1,150,Uttarakhand,"Good guard dog, very alert, active, obedience ...",high,medium,low,intermediate,high,yes,unknown,no
4,850a43f90,dog,Hunter,1,Mixed Breed,NaN,male,Black,NaN,NaN,2,1,2,2,2,1,1,0,Maharashtra,This handsome yet cute boy is up for adoption....,high,medium,low,intermediate,high,maybe,unknown,no

In [92]:
pets.to_csv("pets_clean.csv", index = False)

In [94]:
pets = pd.read_csv("pets_clean.csv")

In [95]:
pets.head()

,PetID,Type,Name,Age,Breed1,Breed2,Gender,Color1,Color2,Color3,MaturitySize,FurLength,Vaccinated,Dewormed,Sterilized,Health,Quantity,Fee,State,Description,energy_level,space_requirement,grooming_level,experience_required,time_requirement,kid_friendly,pet_friendly,special_needs
0,86e1089a3,cat,Nibble,3,Tabby,NaN,male,Black,White,NaN,1,1,2,2,2,1,1,100,Maharashtra,Nibble is a 3+ month old ball of cuteness. He ...,high,small,low,intermediate,high,yes,unknown,no
1,6296e909a,cat,No Name Yet,1,Domestic Medium Hair,NaN,male,Black,Brown,NaN,2,2,3,3,3,1,1,0,Uttarakhand,I just found it alone yesterday near my apartm...,high,medium,medium,intermediate,high,maybe,unknown,no
2,3422e4906,dog,Brisco,1,Mixed Breed,NaN,male,Brown,White,NaN,2,2,1,1,2,1,1,0,Maharashtra,Their pregnant mother was dumped by her irresp...,high,medium,medium,intermediate,high,maybe,unknown,no
3,5842f1ff5,dog,Miko,4,Mixed Breed,NaN,female,Black,Brown,NaN,2,1,1,1,2,1,1,150,Uttarakhand,"Good guard dog, very alert, active, obedience ...",high,medium,low,intermediate,high,yes,unknown,no
4,850a43f90,dog,Hunter,1,Mixed Breed,NaN,male,Black,NaN,NaN,2,1,2,2,2,1,1,0,Maharashtra,This handsome yet cute boy is up for adoption....,high,medium,low,intermediate,high,maybe,unknown,no

In [96]:
new_columns = [
    "monthly_care_cost",
    "vet_visit_frequency",
    "medical_risk",
    "requires_temperature_control",
    "separation_anxiety_risk",
    "shedding_level",
    "expected_lifespan"
]

for col in new_columns:
    pets[col] = None

In [97]:
def monthly_cost(row):

    if row["space_requirement"] in ["large", "extra_large"]:
        return "high"

    if row["grooming_level"] == "high":
        return "high"

    if row["space_requirement"] == "medium":
        return "medium"

    return "low"


pets["monthly_care_cost"] = pets.apply(monthly_cost, axis=1)

In [98]:
def vet_visits(health):

    if health == 1:
        return "low"

    if health == 2:
        return "medium"

    return "high"


pets["vet_visit_frequency"] = pets["Health"].apply(vet_visits)

In [99]:
def medical_risk(health):

    if health == 1:
        return "low"

    if health == 2:
        return "medium"

    return "high"


pets["medical_risk"] = pets["Health"].apply(medical_risk)

In [100]:
def temperature_control(row):

    if row["FurLength"] == 3:
        return "yes"

    if row["space_requirement"] == "small":
        return "maybe"

    return "no"


pets["requires_temperature_control"] = pets.apply(temperature_control, axis=1)

In [101]:
def separation_risk(age):

    if age < 12:
        return "high"

    if age < 60:
        return "medium"

    return "low"


pets["separation_anxiety_risk"] = pets["Age"].apply(separation_risk)

In [102]:
fur_shedding_map = {
    1: "low",
    2: "medium",
    3: "high"
}

pets["shedding_level"] = pets["FurLength"].map(fur_shedding_map)

In [103]:
def lifespan(row):

    if row["Type"] == "dog":
        return "10-13 years"

    return "12-16 years"


pets["expected_lifespan"] = pets.apply(lifespan, axis=1)

In [104]:
pets.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14993 entries, 0 to 14992
Data columns (total 35 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   PetID                         14993 non-null  object
 1   Type                          14993 non-null  object
 2   Name                          13728 non-null  object
 3   Age                           14993 non-null  int64
 4   Breed1                        14988 non-null  object
 5   Breed2                        4231 non-null   object
 6   Gender                        14993 non-null  object
 7   Color1                        14993 non-null  object
 8   Color2                        10522 non-null  object
 9   Color3                        4389 non-null   object
 10  MaturitySize                  14993 non-null  int64
 11  FurLength                     14993 non-null  int64
 12  Vaccinated                    14993 non-null  int64
 13  Dewormed                      14993 non-null  int64
 14  Sterilized                    14993 non-null  int64
 15  Health                        14993 non-null  int64
 16  Quantity                      14993 non-null  int64
 17  Fee                           14993 non-null  int64
 18  State                         14993 non-null  object
 19  Description                   14980 non-null  object
 20  energy_level                  14993 non-null  object
 21  space_requirement             14993 non-null  object
 22  grooming_level                14993 non-null  object
 23  experience_required           14993 non-null  object
 24  time_requirement              14993 non-null  object
 25  kid_friendly                  14993 non-null  object
 26  pet_friendly                  14993 non-null  object
 27  special_needs                 14993 non-null  object
 28  monthly_care_cost             14993 non-null  object
 29  vet_visit_frequency           14993 non-null  object
 30  medical_risk                  14993 non-null  object
 31  requires_temperature_control  14993 non-null  object
 32  separation_anxiety_risk       14993 non-null  object
 33  shedding_level                14993 non-null  object
 34  expected_lifespan             14993 non-null  object
dtypes: int64(9), object(26)
memory usage: 4.0+ MB

In [105]:
pets = pets.drop(columns=["Color2", "Color3", "Quantity", "Fee"])

In [106]:
pets["Name"] = pets["Name"].fillna("Unnamed Pet")

In [107]:
pets["Breed2"] = pets["Breed2"].fillna("Mixed")

In [108]:
def display_breed(row):
    if row["Breed2"] == "Mixed":
        return f"{row['Breed1']} mix"
    return row["Breed1"]

pets["display_breed"] = pets.apply(display_breed, axis=1)

In [109]:
pets.to_csv("pets_dataset_final.csv", index=False)

In [110]:
final = pd.read_csv("pets_dataset_final.csv")

In [111]:
import numpy as np

choices = ["yes", "maybe", "no"]

final["pet_friendly"] = np.random.choice(choices, size=len(train))

In [113]:
final["pet_friendly"].value_counts()

pet_friendly
no       5019
yes      4999
maybe    4975
Name: count, dtype: int64

In [114]:
final.to_csv("pets_dataset_final.csv", index=False)